sequentech/common-ui

themes/podemos/app.less

These styles only had been test in browser console.

Make view-link allways visible and some css customization in podemos theme

---

avRegistration/login-directive/login-directive.js
dist/appCommon-v5.0.1.js

isFirst should indicate if it's the first token, not the first election in the natural order list.

fixing isFirst in vote-permission-token processing

---

package.json
yarn.lock

Reported issues:
https://github.com/agoravoting/agora-gui-common/security/dependabot/6
https://github.com/agoravoting/agora-gui-common/security/dependabot/3
https://github.com/agoravoting/agora-gui-common/security/dependabot/11

Fixing some security issues that dependabot reported but couldn't solve

---

package.json
yarn.lock

Fixes https://github.com/sequentech/common-ui/security/dependabot/15

bump async to 3.2.2

---

package.json
yarn.lock

Fixes https://github.com/sequentech/common-ui/security/dependabot/19

Bump semver-regex from 3.1.3 to 3.1.4

---

dist/themes/default/app.less
themes/default/app.less

This is a follow-up on https://github.com/sequentech/common-ui/pull/219

Change button success colors

---

avRegistration/login-directive/login-directive.js
avRegistration/logout-controller/logout-controller.js
dist/appCommon-vmaster.js

Redirect back to path stored in session storage after a successful login.

Redirect to path after admin login

---

avUi/change-lang-directive/change-lang-directive.js
avUi/i18n-override-service.js
dist/appCommon-vmaster.js
index.html

* load i18n overrides during language changes
* adding i18noverride service

load i18n overrides during language changes

---

dist/libCommon-v6.1.5.js
package.json
yarn.lock

Include changes to master from[ this PR.](https://github.com/sequentech/common-ui/pull/236)

Security update (6.1.x)

---

dist/libCommon-v6.1.5.js
package.json
yarn.lock

Include changes to master from [this PR.](https://github.com/sequentech/common-ui/pull/239)

Bump moment version 

---

package.json
yarn.lock

Include changes to master from [this PR.](https://github.com/sequentech/common-ui/pull/242)

Force Moment version

---

SequentConfig.js
avRegistration/auth-method-service.js
dist/SequentConfig-v6.1.5.js
dist/appCommon-v6.1.5.js

Include changes from [this PR](https://github.com/sequentech/common-ui/pull/244) in version 6.1.x

Support HTML format when sending email auth-codes

---

avRegistration/auth-method-service.js
dist/appCommon-v7.0.0-beta.1.js

Include changes from [this PR](https://github.com/sequentech/common-ui/pull/246) in version 7.0.x

Support sending reminders to voters who didn't cast a vote

---

avRegistration/login-directive/login-directive.js
dist/appCommon-vmaster.js

* Set variable in session storage after login in to indicate whether the user can see the PDF.
Previous PR: https://github.com/sequentech/common-ui/pull/248

Support showing PDF in start-screen 

---

dist/libCommon-v7.0.0-beta.1.js
yarn.lock

[Merge features into 7.1.x](https://github.com/sequentech/common-ui/pull/254)

Bump socket.io-parser from 4.0.4 to 4.0.5

---

dist/libCommon-v6.1.6.js
yarn.lock

[Merge features into 6.1.x](https://github.com/sequentech/common-ui/pull/254)

Bump socket.io-parser from 4.0.4 to 4.0.5 (#254)

---

avRegistration/auth-method-service.js
dist/appCommon-vmaster.js
dist/libCommon-vmaster.js

Automate filling in election IDs. If the election ID in the Election JSON is negative, replace it with new Election IDs.
* Add method that makes request to IAM endpoint to get the highest election ID.

Election IDs automation

---

avRegistration/auth-method-service.js
dist/appCommon-v7.1.1.js

Automate filling in election IDs. If the election ID in the Election JSON is negative, replace it with new Election IDs.
* Add method that makes request to IAM endpoint to get the highest election ID.

Election IDs automation (#267)

---

dist/libCommon-v7.2.0.js
package.json
yarn.lock

Fixes https://github.com/sequentech/common-ui/security/dependabot/40

Bump xml2js from 0.4.17 to 0.5.0

---

dist/libCommon-vmaster.js
package.json
yarn.lock

Fixes https://github.com/sequentech/common-ui/security/dependabot/40

Bump xml2js from 0.4.17 to 0.5.0 (#287)

---

.github/workflows/ort.yml

Parent issue: https://github.com/sequentech/meta/issues/59
Use the reusable workflow from the meta repository instead.

Fix ORT Github Workflow (#290)

---

avUi/i18n-override-service.js
dist/appCommon-vmaster.js

Parent issue: https://github.com/sequentech/voting-booth/issues/321

🐞 dynamic translation issues

---

SequentConfig.js
avRegistration/auth-method-service.js
dist/SequentConfig-v9.0.0.js
dist/appCommon-v9.0.0.js

Parent issue: https://github.com/sequentech/meta/issues/119

🐞 add census data second batch will not be executed (#322)

---

package.json
yarn.lock

Parent issue: https://github.com/sequentech/meta/issues/230
Fixes https://github.com/sequentech/common-ui/security/dependabot/48

Bump tough-cookie to 4.1.3 (#339)

---

avRegistration/auth-method-service.js
avUi/election-creation.js
dist/appCommon-v9.1.0.js

Parent issue: https://github.com/sequentech/meta/issues/124

Automated start/stop support

---

avRegistration/login-directive/login-directive.js
dist/appCommon-v10.0.0.js

Parent issue: https://github.com/sequentech/meta/issues/260

Fix uri params with spaces

---

avUi/checker-service.js
dist/appCommon-v10.0.0.js

Parent issue: https://github.com/sequentech/meta/issues/268

🐞 election-title_i18n is not applied everywhere

---

avUi/checker-service.js
dist/appCommon-vmaster.js

Parent issue: https://github.com/sequentech/meta/issues/268

🐞 election-title_i18n is not applied everywhere (#349)

---

avUi/change-lang-directive/change-lang-directive.js
dist/appCommon-vmaster.js

Parent issue: https://github.com/sequentech/meta/issues/287

🐞 switching between translations with custom texts doesn't work (#356)

---

avRegistration/auth-method-service.js
dist/appCommon-v10.0.2.js

Parent issue: https://github.com/sequentech/meta/issues/310

🐞 Sending credentials to an email-otp auth-method sends empty subject email

---

avUi/change-lang-directive/change-lang-directive.js
dist/appCommon-vmaster.js

Parent issue: https://github.com/sequentech/meta/issues/315

🐞 default translation appears when switching language for the first time

---

avUi/change-lang-directive/change-lang-directive.js
dist/appCommon-v10.0.2.js

Parent issue: https://github.com/sequentech/meta/issues/320

🐞 Fix translations

---

avUi/change-lang-directive/change-lang-directive.js
dist/appCommon-vmaster.js

Parent issue: https://github.com/sequentech/meta/issues/320

🐞 Fix translations (#364)

---

avUi/change-lang-directive/change-lang-directive.js
dist/appCommon-vmaster.js

Parent issue: https://github.com/sequentech/meta/issues/320

🐞 Fix translations (#366)

---

avUi/change-lang-directive/change-lang-directive.js
avUi/i18n-override-service.js
dist/appCommon-v10.0.2.js

Parent issue: https://github.com/sequentech/meta/issues/306

 ✨ Select languages per election

---

avUi/change-lang-directive/change-lang-directive.js
avUi/i18n-override-service.js
dist/appCommon-vmaster.js

Parent issue: https://github.com/sequentech/meta/issues/306

 ✨ Select languages per election (#369)

---

avUi/i18n-override-service.js
dist/appCommon-v10.1.0.js

Parent issue: https://github.com/sequentech/meta/issues/315

 🐞 default translation appears when switching language for the first time 

---

avUi/i18n-override-service.js
dist/appCommon-vmaster.js

Parent issue: https://github.com/sequentech/meta/issues/315

 🐞 default translation appears when switching language for the first time  (#373)

---

avRegistration/login-controller/login-controller-spec.js
avRegistration/login-directive/login-directive.js
avRegistration/logout-controller/logout-controller.js
avRegistration/register-controller/register-controller.js
avRegistration/register-directive/register-directive.js
avUi/i18n-override-service.js
avUi/show-versions-modal-service.js
dist/appCommon-vmaster.js

Parent issue: https://github.com/sequentech/meta/issues/315
Trying to resolve some issues with i18next

🐞 default translation appears when switching language for the first time (#377)

---

package.json
yarn.lock

Parent issue: https://github.com/sequentech/meta/issues/567
Dependabot tickets:
- https://github.com/sequentech/common-ui/security/dependabot/52
- https://github.com/sequentech/common-ui/security/dependabot/51

Security dependencies update (#380)

---

avRegistration/auth-method-service.js
dist/appCommon-vmaster.js

Parent issue: https://github.com/sequentech/meta/issues/209
- Add api call to download turnout to auth api.

✨ Download election turnout (#387)

---

avRegistration/login-directive/login-directive.js
dist/appCommon-vmaster.js

Parent issue: https://github.com/sequentech/meta/issues/716

🐞 OIDC: Use Authorization Code Flow instead of implicit flow (#388)

---

avRegistration/login-directive/login-directive.js
dist/appCommon-vmaster.js

Parent issue: https://github.com/sequentech/meta/issues/913

🐞 Can't login on alt auth method with openid as main (#395)

---

avRegistration/auth-method-service.js
dist/appCommon-v10.4.2.js

Parent issue: https://github.com/sequentech/meta/issues/752

✨🐞 Improve/rethink/fix Live Preview

---

avRegistration/auth-method-service.js
dist/appCommon-v10.4.2.js

Parent issue: https://github.com/sequentech/meta/issues/205

✨ Increase the timeout due to user activity

---

avRegistration/auth-method-service.js
dist/appCommon-vmaster.js

Parent issue: https://github.com/sequentech/meta/issues/752

✨🐞 Improve/rethink/fix Live Preview (#400)

---

avRegistration/login-directive/login-directive.js
dist/appCommon-v10.4.2.js

Parent issue: https://github.com/sequentech/meta/issues/234

✨ Voter eligibility check

---

avRegistration/auth-method-service.js
dist/appCommon-vmaster.js

Parent issue: https://github.com/sequentech/meta/issues/205
---------

✨ Increase the timeout due to user activity (#399)

---

avRegistration/auth-method-service.js
avRegistration/login-directive/login-directive.js
avUi/common-header-directive/common-header-directive.js
dist/appCommon-vmaster.js

Parent issue: https://github.com/sequentech/meta/issues/762

✨ Separation of voting session time and bearer token lifetime

---

avRegistration/auth-method-service.js
dist/appCommon-v10.4.2.js

Parent issue: https://github.com/sequentech/meta/issues/1832

🐞 Login error for voters

---

avRegistration/auth-method-service.js
dist/appCommon-v10.5.0.js

Parent issue: https://github.com/sequentech/meta/issues/1832

🐞 Login error for voters (#409)
